/**:
  ros__parameters:
    dir_logs: "Desktop/logs"
    dirs_sub:
      - "test"
    topics:
      - "/flir2/image_raw"
      # - "/mess2/flir1/meta"
      # - "/mess2/flir2/camera_info"
      # - "/mess2/flir2/meta"
    period_timer: 5.0