/**:
  ros__parameters:
    dir_logs: "Projets/testing"
    dirs_sub:
      - "flir"
    topics:
      - "/mess2/flir1/camera_info"
      - "/mess2/flir1/meta"
      - "/mess2/flir2/camera_info"
      - "/mess2/flir2/meta"
    period_timer: 5.0